//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferenciaCalculadora
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/CalculadoraSOAP")]
    public partial class Error : object
    {
        
        private string codigoField;
        
        private string mensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaCalculadora.ICalculadora")]
    public interface ICalculadora
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadora/SumaValores", ReplyAction="http://tempuri.org/ICalculadora/SumaValoresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ReferenciaCalculadora.Error), Action="http://tempuri.org/ICalculadora/SumaValoresErrorFault", Name="Error", Namespace="http://schemas.datacontract.org/2004/07/CalculadoraSOAP")]
        System.Threading.Tasks.Task<int> SumaValoresAsync(int v1, int v2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadora/RestaValores", ReplyAction="http://tempuri.org/ICalculadora/RestaValoresResponse")]
        System.Threading.Tasks.Task<int> RestaValoresAsync(int v1, int v2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadora/DivideValoresLanza", ReplyAction="http://tempuri.org/ICalculadora/DivideValoresLanzaResponse")]
        System.Threading.Tasks.Task<int> DivideValoresLanzaAsync(int v1, int v2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadora/DivideValoresGestiona", ReplyAction="http://tempuri.org/ICalculadora/DivideValoresGestionaResponse")]
        System.Threading.Tasks.Task<int> DivideValoresGestionaAsync(int v1, int v2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface ICalculadoraChannel : ReferenciaCalculadora.ICalculadora, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class CalculadoraClient : System.ServiceModel.ClientBase<ReferenciaCalculadora.ICalculadora>, ReferenciaCalculadora.ICalculadora
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CalculadoraClient() : 
                base(CalculadoraClient.GetDefaultBinding(), CalculadoraClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICalculadora.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculadoraClient(EndpointConfiguration endpointConfiguration) : 
                base(CalculadoraClient.GetBindingForEndpoint(endpointConfiguration), CalculadoraClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculadoraClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CalculadoraClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculadoraClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CalculadoraClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculadoraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> SumaValoresAsync(int v1, int v2)
        {
            return base.Channel.SumaValoresAsync(v1, v2);
        }
        
        public System.Threading.Tasks.Task<int> RestaValoresAsync(int v1, int v2)
        {
            return base.Channel.RestaValoresAsync(v1, v2);
        }
        
        public System.Threading.Tasks.Task<int> DivideValoresLanzaAsync(int v1, int v2)
        {
            return base.Channel.DivideValoresLanzaAsync(v1, v2);
        }
        
        public System.Threading.Tasks.Task<int> DivideValoresGestionaAsync(int v1, int v2)
        {
            return base.Channel.DivideValoresGestionaAsync(v1, v2);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICalculadora))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICalculadora))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:52075/Calculadora.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CalculadoraClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICalculadora);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CalculadoraClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICalculadora);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICalculadora,
        }
    }
}
